<?xml version="1.0" ?>



<robot name="arm" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- This is the core -->
    <xacro:property name="arm_base_length" value="0.1" />
    <xacro:property name="arm_base_width" value="0.1" />
    <xacro:property name="arm_base_height" value="0.02" />

    <xacro:property name="forearm_radius" value="0.02" />
    <xacro:property name="forearm_height" value="0.3" />

    <xacro:property name="hand_link_radius" value="0.02" />
    <xacro:property name="hand_link_height" value="0.3" />
    
    <!-- <xacro:property name="base_length" value="0.6" />
    <xacro:property name="base_width" value="0.4" />
    <xacro:property name="base_height" value="0.2" /> -->

    <joint name="base_arm_base_joint" type="fixed">
        <parent link="base_link" />
        <child link="arm_base_link" />
        <origin xyz="${base_length/4} 0 ${base_height}" />
    </joint>

    <link name="arm_base_link">
        <visual>
            <geometry>
                <box size="${arm_base_length} ${arm_base_width} ${arm_base_height}" />
            </geometry>
            <origin xyz="0 0 ${arm_base_height/2.0}" rpy="0 0 0"/>
            <material name="orange" />
        </visual>
        <xacro:box_inertia m="0.5" x="${arm_base_length}" y="${arm_base_width}" z="${arm_base_height}"
                           o_xyz="0 0 ${arm_base_height/2.0}" o_rpy="0 0 0"/>

        <collision>
            <geometry>
                <box size="${arm_base_length} ${arm_base_width} ${arm_base_height}" />
            </geometry>
            <origin xyz="0 0 ${arm_base_height/2.0}" rpy="0 0 0"/>
        </collision>
    </link>

    <joint name="arm_base_forearm_joint" type="revolute">
        <parent link="arm_base_link" />
        <child link="forearm_link" />
        <origin xyz="0 0 ${arm_base_height}" />
        <axis xyz="0 1 0" />
        <limit lower="0" upper="${pi/2}" effort="100" velocity="100" />
        <dynamics friction="0.3" damping="0.3"/>

    </joint>

    <link name="forearm_link">
        <visual>
            <geometry>
                <cylinder radius="${forearm_radius}" length="${forearm_height}" />
            </geometry>
            <origin xyz="0 0 ${forearm_height/2}" rpy="0 0 0" />
            <material name="yellow" />
        </visual>
        <xacro:cylinder_inertia m="0.3" r="${forearm_radius}" h="${forearm_height}"
                                o_xyz="0 0 ${forearm_height/2}" o_rpy="0 0 0"/>

        <collision>
            <geometry>
                <cylinder radius="${forearm_radius}" length="${forearm_height}" />
            </geometry>
            <origin xyz="0 0 ${forearm_height/2}" rpy="0 0 0" />
        </collision>
    </link>

    <joint name="forearm_hand_joint" type="revolute">
        <parent link="forearm_link" />
        <child link="hand_link" />
        <origin xyz="0 0 ${forearm_height}" />
        <axis xyz="0 1 0" />
        <limit lower="0" upper="${pi/2}" effort="100" velocity="100" />
        <dynamics friction="0.3" damping="0.3"/>
    </joint>

    <link name="hand_link">
        <visual>
            <geometry>
                <cylinder radius="${hand_link_radius}" length="${hand_link_height}" />
            </geometry>
            <origin xyz="0 0 ${hand_link_height/2}" rpy="0 0 0" />
            <material name="orange" />
        </visual>
        <xacro:cylinder_inertia m="0.3" r="${hand_link_radius}" h="${hand_link_height}"
                                o_xyz="0 0 ${hand_link_height/2}" o_rpy="0 0 0"/>
        
        <collision>
            <geometry>
                <cylinder radius="${hand_link_radius}" length="${hand_link_height}" />
            </geometry>
            <origin xyz="0 0 ${hand_link_height/2}" rpy="0 0 0" />
        </collision>
    </link>

</robot>